name = "cash-track"
main = "src/index.ts"

compatibility_date = "2026-03-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "expenditure"
database_id = "5500f846-5453-434f-8418-3073cfe5077f"
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "RECEIPT_IMAGES"
bucket_name = "expenditure"


